name: project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon1.png"
  adaptive_icon_foreground: "assets/images/text.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Icon_List/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/static/Rubik-Bold.ttf
          weight: 700